### PR TITLE
Fix behavior of conj for lists with multiple arguments

### LINKED ISSUE #308: [clj] Conj is not actually variadic for lists
Given enough arguments, `conj` fails for lists with errors like `clj:conj/8 is not defined`.

I'll get to work on fixing this and adding better tests for `conj` with many arguments as soon as I can, but just putting it out there that it's an issue.

### PR DESCRIPTION
**Pull request by skovsgaard**
Fixes #308.

I can't work out if the argument order is unintuitive, i.e. that the first arguments are prepended first rather than last. If anyone has feedback I'd love to hear some.

### CODE REVIEW

**Comment by yurrriq** [comment]
You can say `#'cons/2` instead, but could we just replace the fold with `(lists:append (lists:reverse (list ,@xs)) ,coll)` or similar?

**Comment by skovsgaard** [comment]
Yup. Turns out we can do pretty much that.

**Review by yurrriq — APPROVED** [review]
LGTM

**Comment by rvirding** [comment]
conj is a mess. Is this compatible with clojure conj?

**Comment by yurrriq** [comment]
As far as I know, it is compatible, yeah.

**Comment by skovsgaard** [comment]
@rvirding, just to be sure: Is this implementation particularly messy or do you mean conj conceptually? Because if we're talking the implementation here, I'd be happy to get to work on cleaning it up.

**Comment by rvirding** [comment]
Could you rebase this and fix it if necessary with the latest definition of conj?

**Comment by skovsgaard** [comment]
I'll rebase it asap. It should be some time later today.

**Comment by skovsgaard** [comment]
Okay, if at all possible, hold this for a second while I figure out where I went wrong in rebasing.

**Comment by skovsgaard** [comment]
There we go. `conj` is now located in the right place in the file and it's updated to the new version. And the branch has been rebased on develop.

**Comment by rvirding** [comment]
I get some really strange behaviour are pulling this request. After pushing it travis runs without errors. HOWEVER if I just try to compile the file `test/clj-test.lfe` manually or run 'make travis' then I get this error:

```
test/clj-tests.lfe:529: unbound function: #(cons 4)
test/clj-tests.lfe:529: unbound function: #(cons 4)
```
I have no idea what is going on and I am trying to chase the error.

**Comment by rvirding** [comment]
Sorry it does work. I just needed to recompile the LFE files and it worked. I must have got some strangeness in my file. Sorry again.

**Pull request merged**
