### PR TITLE
Update lfec and lfedoc

### PR DESCRIPTION
**Pull request by yurrriq**
Add `+no_docs` to terms list per #227.

### CODE REVIEW

**Comment by yurrriq** [comment]
N.B. I'm working on this on my phone while I wait in line for a car wash and plan to include the `lfedoc` changes suggested in #227 before this is ready to go, so don't merge yet.

**Comment by rvirding** [comment]
If you are adding to the options why not change them all to "LFE formats"? So add `no-docs` and convert the others.

**Comment by yurrriq** [comment]
This should be good to go now. Feel free to clean up `lfedoc` as you see fit.

Example output:

```
$ lfedoc test/example.lfe
example
  This is an example module.
----------------------------------------------------------------------

add/2
 ((x y))
 Add `x` and `y`.


varargs/255
 (args)
 This is a varags macro.


forty-two?/2
 ((backquote (,x) (when (=:= x 42)))
  (backquote (,x) (when (< x 42)))
  (backquote (,x) (when (> x 42))))
 Return `'true` iff `x` is 42.


tricky/255
 ((x) (x y) (x y . z))
 This is a tricky varargs macro.


subtract/2
 ((x y))
 Subtract `y` from `x`.


matchfun/3
 ((x y z (when (call 'erlang '< x y) (call 'erlang '< y z)))
  (x y z (when (call 'erlang '> x y) (call 'erlang '> y z)))
  (x y z (when (call 'erlang '=:= x y) (call 'erlang '=:= y z)))
  (_ _ _))
 This is a function with pattern clauses.


$handle_undefined_function/2
 ((f as))


another-example
----------------------------------------------------------------------

divmod/2
 ((n d))


$handle_undefined_function/2
 ((f as))
```

**Comment by yurrriq** [comment]
Note the undesirable output for `forty-two?`, which is now defined:

``` lfe
(defmacro forty-two?
  "Return `'true` iff `x` is 42."
  (`(,x) (when (=:= x 42)) `'yes)
  (`(,x) (when (< x 42))   `'small)
  (`(,x) (when (> x 42))   `'big))
```

If you replace ``(,x)` with `(list x)`:

```
forty-two?/1
 ((x (when (=:= x 42))) (x (when (< x 42))) (x (when (> x 42))))
 Return `'true` iff `x` is 42.
```

**Pull request merged**
