### PR TITLE
Don't quote $shebangs

### PR DESCRIPTION
**Pull request by arpunk**
This fixes the arguments passed to the VM on startup.

### CODE REVIEW

**Comment by yurrriq** [comment]
We should update `R3_PROJ_LIBS` as in `bin/lfe` too, i.e. use `REBAR_DEPS_DIR` if set and search for all `default` lib dirs. Maybe we should update both to check for `REBAR_PROFILE` and use that instead of a hard-coded `default` too.

**Comment by arpunk** [comment]
@yurrriq Currently we load all the `default` dirs from rebar3 if `REBAR_DEPS_DIR` is not present. I see the use of `REBAR_PROFILE` and it comes very handy. Shall I add the commit or should I submit another PR?

**Comment by rvirding** [comment]
Update the commit.

**Comment by yurrriq** [comment]
I must've been looking at a partial diff or something. I think the same PR should be fine.

**Comment by arpunk** [comment]
@yurrriq @rvirding Done.

**Review by yurrriq — APPROVED** [review]

**Comment by rvirding** [comment]
I am pulling this. What problem did quoting the $shebang cause? We quote the $@.

**Pull request merged**
