### PR TITLE
Fix deprecated call `erlang:get_stacktrace/0`

### PR DESCRIPTION
**Pull request by maximvl**
I checked for compilation in both 20 & 22.

### CODE REVIEW

**Comment by oubiwann** [comment]
You might want t rebase on this branch in this PR, which fixes the TravisCI tests:
 * https://github.com/rvirding/lfe/pull/374

Or just wait until @rvirding merges it ... so that you can re-run the tests in Travis against the updates.

**Comment by rvirding** [comment]
I have some quick comments: I would like to define the `CATCH` macro in one place in an include file; maybe have 2 `CATCH` macros, one with the stacktrace and one without, to be more efficient; and probably define a specific environment variable for this as is done for other features which change with erlang version.

Checkout the files `get_comp_opts.escript` and `rebar.config.script` which do this.

Getting rid of calls to erlang:get_stacktrace/0 is a Good Thing though.

**Comment by rvirding** [comment]
I also see I have a lot of other work on LFE which I have to go through. I am on holidays in the country so my internet connection is not good so don't expect too much before august. :smile:

**Comment by maximvl** [comment]
I added the feature macro as you explained: `?NEW_STACKTRACE`, definition of `?CATCH` and `?IS_MAP` moved to `lfe.hrl`.

Also, I cleaned up quoting macros so that only definition is in `lfe_macro.hrl`, `lfe.hrl` now includes it as well for convenience.

Now I'm thinking maybe its better to move feature macros to a separate file like `lfe_features.hrl` and have `lfe.hrl` include all others, what do you think?

**Comment by rvirding** [comment]
Please fork from `develop` not `master`. I only take things from `develop` into `master`. So while I like this PR and if you redo it based on `develop` then I will take it.

It would probably be better not to remove the quote macros from lfe.hrl but include that file and remove the definitions from other files.

**Comment by lin7sh** [comment]
@maximvl Thanks for contribution to this. the deprecation warning is a bit annoying

**Comment by oubiwann** [comment]
I changed the PR to develop, but then saw that the original work was done on top of master and not develop, so I switched it back ...

**Comment by oubiwann** [comment]
I've marked this PR as "blocked," since it needs to done against the develop branch ...

**Comment by lin7sh** [comment]
Just made a PR to rebase this one on develop, it works on OTP 23 too, except for #392

**Comment by rvirding** [comment]
I have closed this one as too many files have been changed after it so merging it would be impossible.

**Pull request closed without merging**
