### PR TITLE
1st draft of REPL/shell server

### LINKED ISSUE #153: Support for headless LFE REPL/shell servers
I have two separate needs for an LFE server: 
1. as part of the try.lfe.io project, and
2. as a backend for IPython/Jupyter

Having an LFE server I could start up and then send code to, with the server tracking the LFE environment (state), would make my life much easier :-)

I have a first draft implementation of this done and I will submit a PR for review.

### PR DESCRIPTION
**Pull request by oubiwann**
Fixes #153

My big question is how to handle the server crashing with bad input. I've tried various incantations of trap exit, all to no avail. I would like to _not_ lose the environment when there's a crash.

Additional questions:
- I was thinking of ways in which I might be able to selectively capture `stdout`, e.g., when calling `(help)` on the headless LFE shell server ... but I'm guessing I'd need to export more of the `lfe_shell` functions so I could override the default io device ... ?
- I was also thinking about moving `lfe_shell:server` to `lfe_server:new`, thus providing a single home for things called "LFE servers", but where one was a `gen_server` and the other a custom looping process.
- A follow-up/alternative to the last question: Are you interested in generalizing the LFE server into something that would support both standard, interactive use as well a headless version?

A few things to note:
- to avoid duplicating code, I had to add three more functions to be exported by `lfe_shell`
- I had to put the code which writes to stdout into a `case` block (and add another arity for `eval_form`)
- the docs mention the crashing: this will be updated when a solution is in place

### CODE REVIEW

**Comment by oubiwann** [comment]
Oh, wow -- I don't need to do anything convoluted to capture stdout -- you already handle it quite nicely!

``` lfe
> (lfe_server:send '(help))

LFE shell built-in functions

(c file)    -- compile and load code in <file>
(cd dir)    -- change working directory to <dir>
(ec file)   -- compile and load code in erlang <file>
(exit)      -- quit - an alias for (q)
(help)      -- help info
(i)         -- information about the system
(l module)  -- load or reload <module>
(ls)        -- list files in the current directory
(clear)     -- clear the the REPL output
(ls dir)    -- list files in directory <dir>
(m)         -- which modules are loaded
(m mod)     -- information about module <mod>
(pid x y z) -- convert <x>, <y> and <z> to a pid
(pwd)       -- print working directory
(q)         -- quit - shorthand for init:stop/0
(flush)     -- flushes all messages sent to the shell
(regs)      -- information about registered processes

LFE shell built-in commands

(reset-environment)             -- resets the environment to its initial state
(set pattern expr)
(set pattern (when guard) expr) -- evaluate <expr> and match the result with
                                   pattern binding
(slurp file)                    -- slurp in a LFE source <file> and makes
                                   everything available in the shell
(unslurp)                       -- revert back to the state before the last
                                   slurp
(run file)                      -- execute all the shell commands in a <file>

LFE shell built-in variables

+/++/+++      -- the tree previous expressions
*/**/***      -- the values of the previous expressions
-             -- the current expression output
$ENV          -- the current LFE environment

ok
```

**Update**: If I need to do anything special with the results that get sent back to the server and displayed in the server's stdout, I can always do that server-side.

**Comment by rvirding** [comment]
The reason this works is that the shell sends its output, and the output from all processes it starts, to the same default output as the process which makes the call.
How you implement this interface depends very much how you want to run it the shell:
- If you want the shell as normally but just be able to control from/to where it reads/writes then there is a much easier method.
- If you want to use the shell as an evaluator where you pass in a (list of) form and get back a value then it becomes a little more complicated because of the io. It is not just a matter of not printing the return value but of catching all output from the shell commands.

Maybe it would be better with a small internal redesign to make it easier to handle this various alternatives.

**Comment by oubiwann** [comment]
That would be cool to support more uses of the shell/repl server.

This is a bit obvious, but I'll suggest it anyway :-) What about returning something like:

``` lfe
`(#(result ,result)
  #(stdout ,collected-out-iolist)
  #(stderr ,collected-err-iolist))
```

If would mean:
- adding an extra output-agnostic layer (wherever the real work is being done)
- converting all `io:*` calls to `io_lib:*` calls with an append to the appropriate iolist accumulator,
- returning the proposed proplist to a new "top layer" which would then
- print to stderr and stdout or return to the calling function, as appropriate (based upon how it was called, etc.)

Were you thinking of something like that?

**Comment by rvirding** [comment]
I will pull this into a separate branch as I think it still needs a lot of work, for example with the io. I would like to see some example code of how you intend to use it.

**Comment by oubiwann** [comment]
I think I'd like to pick this work back up. The original use case for this was to support a "headless" LFE REPL that could be sent messages containing sexprs and eval them, just as if a user was interacting in a regular REPL session. The reason we were needing a headless REPL was for supporting try.lfe.io.

Tonight, a new use case came up: per @yurrriq's comment in #236 it would be nice if users could set the LFE prompt dynamically, from within a running REPL. If we were using a gen_server to power the LFE REPL, we could keep the REPL value in the gen_server state data and update the prompt with a gen_server call.

This led me to another use case, mentioned in PR #237: it would be great to support multiple environments and allow users to switch between these in a single REPL session. We'd talked about this at the first LFE summit in Stockholm in 2014. Again, if the LFE REPL was powered by a gen_server, we'd be able to maintain separate user environments, name them, and then swap them out with a gen_server call.

Admittedly the code in this PR doesn't get us to _that point_ ... but it gets us closer :-)

Anyway, the branch is stale now and needs to be rebased. I'll get it updated and pushed, and we can pick this conversation up again ...

**Comment by oubiwann** [comment]
Quick note: I started working on improved error handling last night, once I got the branch rebased. I'll get that pushed once it's working as expected.

Also: now that we have `.lfe` files in the source, I'll probably convert this to LFE :-)

**Comment by oubiwann** [comment]
So much has changed in LFE internals that this work would have to start over. I'm going to close this PR but keep the source ticket open for possible exploration.

**Pull request closed without merging**
