### PR TITLE
Update lfe_io_pretty handling of (map ...) forms

### LINKED ISSUE #183: lfe_io_pretty:term/1 is not so pretty for (map k0 v0 ... kn vn)
I'm mostly leaving this here as a note to self. I'd like to take a stab at this when I get time, unless someone else wants to beat me to it.

Real world example output:

``` lfe
(map
 #"id"
 id
 #"name"
 name
 #"known_by"
 known_by
 #"bio"
 bio
 #"image"
 image
 #"topics"
 topics
 #"links"
 links)
```

`#m(....)` forms are handed differently, if not preferably:

``` lfe
`#M(#"date_modified" ,date_modified
    #"date_published" ,date_published #"id" ,id #"masters" ,masters
    #"sections" ,sections #"slug" ,slug #"summary" ,summary
    #"thumbnail" ,thumbnail #"title" ,title)
```

It'd be cool to align keys and/or values, but it seems like that might easily become a fool's errand. What's more, that style is probably a matter of personal (and subjective) taste.

All things considered, I'd be fine with `(map ...)` forms being printed as `#m(...)` ones are currently, potentially with the precondition that `(> (length form) 2)`, so as not to mess up any `*:map/2` forms.

### PR DESCRIPTION
**Pull request by yurrriq**
Add clause to lfe_io_pretty:term/4 to handle (map ...) forms as maps,
abstracting away F in map/4 to map/5 for maximum code reuse.

Fixes #183.

### CODE REVIEW

**Comment by rvirding** [comment]
There are two problems with your solution:
- the `(map ...)` form is a constructor not a literal so it should print as `(map ...)` not as `#M(...)`
- as it is "hand-written" it could wrongly contain an odd number of elements which must be printed

Otherwise yes.

**Comment by yurrriq** [comment]
Ah, right. Will revise.

**Comment by yurrriq** [comment]
Updated. I've also handled the indentation properly now.

---

Assume the following helper function for these examples:

``` lfe
> (defun println (x) (lfe_io:format "~p\n" `[,x]))
println
```

---

`#m(...)` example:

```
> (println '#m(#"silly" #"example" #"with" #"lots" #"of" #"keys"
               #"and" #"values" #"to" #"test" #"changes" #"to"
               #"lfe_io_pretty" #"wrt" #"map literal" #"forms"
               #"and" #"also" #"(map ...)" #"forms"))
#M(#"(map ...)" #"forms" #"and" #"also" #"changes" #"to"
   #"lfe_io_pretty" #"wrt" #"map literal" #"forms" #"of" #"keys"
   #"silly" #"example" #"to" #"test" #"with" #"lots")
ok
```

---

`(map ...)` example:

```
> (println '(map #"silly" #"example" #"with" #"lots" #"of" #"keys"
                 #"and" #"values" #"to" #"test" #"changes" #"to"
                 #"lfe_io_pretty" #"wrt" #"map literal" #"forms"
                 #"and" #"also" #"(map ...)" #"forms"))
(map #"silly" #"example" #"with" #"lots" #"of" #"keys"
     #"and" #"values" #"to" #"test" #"changes" #"to"
     #"lfe_io_pretty" #"wrt" #"map literal" #"forms" #"and" #"also"
     #"(map ...)" #"forms")
ok
```

---

The `#m(...)` behaviour is unchanged, but previously `(map ...)` forms used to look like this:

```
(map
 #"silly"
 #"example"
 #"with"
 #"lots"
 #"of"
 #"keys"
 #"and"
 #"values"
 #"to"
 #"test"
 #"changes"
 #"to"
 #"lfe_io_pretty"
 #"wrt"
 #"map literal"
 #"forms"
 #"and"
 #"also"
 #"(map ...)"
 #"forms")
```

**Comment by rvirding** [comment]
Only one more problem: what happens if `(map ...)` is not given a sequence of key/value element pairs, i.e. an odd number of elements? Now it seems like the extra element is thrown away which must not be done as this is a valid list even if it is an illegal call.

Just to be difficult. :-)

**Comment by yurrriq** [comment]
You're quite right. It currently throws away the extra term. I'll have to add a special case and append the extra term when present.

**Comment by yurrriq** [comment]
Updated again, namely adding:

``` erlang
    case length(Map) rem 2 of                   %Odd number of elements
        0 -> [P,Body,$)];
        1 -> [P,Body,$\s,term(lists:last(Map), D, I, L),$)]
    end.
```

such that

```
> (println '(map #"an" #"odd" #"number" #"of" #"fields"))
(map #"an" #"odd" #"number" #"of" #"fields")
ok
```

**Comment by yurrriq** [comment]
Oops. That breaks `#m(...)` handling...

**Comment by rvirding** [comment]
These things are sent to try us. :-)

**Comment by yurrriq** [comment]
:hurtrealbad: This latest hack does everything correctly, but ignores line wrapping for the odd element:

``` erlang
term(lists:last(Map), D, 0, 99999)
```

```
$ lfe -eval '(lfe_io:format "~p\n" \'[(map #"an" #"odd" #"number" #"of" #"fields")])'
(map #"an" #"odd" #"number" #"of" #"fields")
```

```
$ lfe -eval '(lfe_io:format "~p\n" \'[#M(#"an" #"odd" #"number" #"of" #"fields")])'
lfe:1: bad map
```

```
$ lfe -eval '(lfe_io:format "~p\n" \'[#M(#"even" #"number" #"of" #"fields")])'
#M(#"even" #"number" #"of" #"fields")
```

**Comment by rvirding** [comment]
Could you just rebase this and I will pull it?

**Comment by yurrriq** [comment]
Will do when back to keyboard.

**Pull request merged**
