### PR TITLE
[clj] Add iff-let (née when-let)

### LINKED ISSUE #272: [clj] Implement when-let
``` clj
(when-let [result (foo x)]
  (do-something-with result)
  (do-something-more-with result))
```

https://github.com/lfex/clj/issues/9

### PR DESCRIPTION
**Pull request by yurrriq**
Depends on #305 and #306, and closes #272.

### CODE REVIEW

**Comment by yurrriq** [comment]
Rebased and removed the extraneous `progn`.

**Comment by rvirding** [comment]
Sorry, I have missed something there. Why can't you call it `when-let` as it is called in clojure?

**Comment by yurrriq** [comment]
I definitely can. The reason I've called it `iff-let` is because I've called Clojure's `when` `iff` to avoid conflicts with guards. I feel like `iff` and `iff-let` makes more sense than `iff` and `when-let`.

With that said, I'm not married to this naming convention. Is it possible/sensible to to define a `when` macro?

**Comment by rvirding** [comment]
You can currently define a macro called `when` and it will be used. If you do this then you cannot have guards anywhere the `when` macro is defined. This is a a core form I missed and the bug will be fixed in the next push I make. After this it will behave like macros with names which a core forms: you can define them but they will be ignored. So you can define a macro called `lambda` but it will be ignored. Perhaps I should make it an error to do this.

**Pull request merged**
