### PR TITLE
Add clj module

### PR DESCRIPTION
**Pull request by yurrriq**
:tada: This PR is **finally** ready! :tada:

The [docs](https://github.com/yurrriq/lfe/blob/feature/add-clojure-lib/doc/src/lfe_clj.3.md) could use a once-over, but are mostly copied (and slightly tweaked) from the docstrings themselves and comments from @dysinger, @oubiwann, et al. from [lfex/clj](https://github.com/lfex/clj).

Everything else should be pretty solid. All the new functions and macros are [tested](https://github.com/yurrriq/lfe/blob/feature/add-clojure-lib/test/clj-tests.lfe) and those that aren't are just aliases for BIFs or are otherwise trivial.

### CODE REVIEW

**Comment by yurrriq** [comment]
Looks like the tests aren't running...

**Comment by yurrriq** [comment]
Closing and reopening to try to trigger a retest.

**Comment by yurrriq** [comment]
```
Top 10 slowest tests (0.016 seconds, 5.6% of total time):
  clj-tests:comp_test/0
    0.009 seconds
  clj-tests:repeat_test/0
    0.005 seconds
  clj-tests:identity_test/0
    0.002 seconds
  clj-tests:record?_test/0
    0.000 seconds
  clj-tests:not=_test/0
    0.000 seconds
  clj-tests:neg?_test/0
    0.000 seconds
  clj-tests:cond_>>_test/0
    0.000 seconds
  clj-tests:undef?_test/0
    0.000 seconds
  clj-tests:boolean?_test/0
    0.000 seconds
  clj-tests:element?_test/0
    0.000 seconds
Finished in 0.287 seconds
71 tests, 0 failures
```

:tada: 60f6205 fixed the Travis config.

**Comment by yurrriq** [comment]
I spotted a typo in the docs already...

> The have since been modified...

should be

> They have since been modified...

**Comment by yurrriq** [comment]
:tada: I've opened issues prefixed with `[clj]` for the remaining ones from lfex/clj. Managed to knock out a couple before the merge too.

**Comment by rvirding** [comment]
I have a little trouble running the final function -get-in-map. I think the HAS_MAPS macro returns something too deep. It returns a form which when you call it builds a call to the BIF so using it in the 'if' does not generate true/false but the call to the BIF.

**Comment by yurrriq** [comment]
Looks like there's not test coverage for `get-in` with maps either. I'll investigate.

**Pull request merged**
