### PR TITLE
Updated dockerfile.

### PR DESCRIPTION
**Pull request by oubiwann**
This was used to update the lfex/lfe and lfex/lfe-docs Dockerhub images. In
addition to some minor cleanup, it did the following:
- Upgraded the dockerfile to use Erlang 19.1
- Upgraded LFE to use the latest dev version, 1.3-dev

### CODE REVIEW

**Comment by rvirding** [comment]
Could you please rebase this and I will pull it.

**Comment by yurrriq** [comment]
Any interest in an Alpine-based image? I've got one lying around.

**Comment by rvirding** [comment]
What is an Alpine-based image?

**Comment by oubiwann** [comment]
@rvirding Done!

@yurrriq It would probably make sense for other changes to the Dockerfile to go in a separate PR ...

**Comment by oubiwann** [comment]
@yurrriq Actually, there's already a project that tracks miscellaneous LFE docker images:
- https://github.com/lfex/dockerfiles

That might be the best place for the Alpine-based image...

**Comment by yurrriq** [comment]
Cool!

**Comment by oubiwann** [comment]
@rvirding Would you rather we simplify the LFE repo, and remove the `Dockerfile` and docker-related `make` targets? We could make an entry in the README pointing to Dockerhub and the `lfex/dockerfiles` repo ...

**Comment by rvirding** [comment]
No, not really. I have nothing against having it there. I just wasn't aware that you had to do specific dockers for different systems (logical really) and then just wondered why we have one and not many. Also when we get olp working and standard then the problem should be moved there in some way.

**Comment by rvirding** [comment]
I clicked the squash and merge button by mistake so the original branch has not been removed. Sorry about that.

You will have to remove the original branch to get rid of it.

**Pull request merged**
