### PR TITLE
Migrate canonical LFE docs from .txt to .md 

### PR DESCRIPTION
**Pull request by oubiwann**
This change does the following:
- Moves the `doc/*.txt` files to `doc/source/*.md`
- Generates new `doc/*.txt` files from the Markdown source
- Generates LFE man pages from the Markdown source
- Provides `make` targets for performing these tasks as well as generating `.pdf` and `.epub` versions of the LFE docs
- Provides a `doc/Dockerfile` for generating a Docker image that can generate the docs
- Provides `make` targets for working with the Docker-based LFE docs
- Adds documentation/instructions for generating LFE docs natively or with Docker

This change fixes issue #206.

### CODE REVIEW

**Comment by oubiwann** [comment]
New docs for this change:
- A `README` in the `doc` directory - https://github.com/oubiwann/lfe/tree/docs2md/doc
- Instructions for updating LFE docs - https://github.com/oubiwann/lfe/blob/docs2md/doc/source/updating_docs.md

**Comment by rvirding** [comment]
Could you make one change to the Makefile? Now if you do `make docs`, like I did first off, it deletes all the documentation and tries to rebuild it from source. Which bombs if you don't have pandoc. Could it be more conventional and just rebuild things which need to be rebuilt.

My second question is how can we use this from the lfe.io page?

**Comment by oubiwann** [comment]
> Could you make one change to the Makefile? Now if you do make docs, like I did first off, it deletes all the documentation and tries to rebuild it from source. Which bombs if you don't have pandoc. Could it be more conventional and just rebuild things which need to be rebuilt.

Yes. That's actually how it was set up, but I spent a couple of hours debugging an issue that was actually not a real issue -- just hidden by the fact that some of the docs weren't getting generated since they existed, even though their sources had changed. [1]

I'll pull out the `clean-docs` target from the `docs` target -- that will fix it. I'll just make sure that when I'm working on the docs, I'll use the clean target all the time first.

---

[1] Correction: the sources hadn't changed -- the command options in the `make` targets had changed.

**Comment by oubiwann** [comment]
Done.

**Comment by oubiwann** [comment]
> My second question is how can we use this from the lfe.io page?

The answer to your second question is much more involved. Most of the details on _how_ this will get done are here:
- https://github.com/lfe/docs3/issues/1

In essence, we're moving away from the ruby-based Jekyll page generator and we're building some tools for doing it ourselves using LFE. (This will eventually get pulled into the Dragon project.)

But there's more to it, with more context than that.

Of the several good reasons we have for building our own static site generator, the one that applies most to your question above is that it will give us the ability to pull in `.md` files from other documentation projects, integrating them seamlessly into the new version of the docs.lfe.io site.

Some more background info for you:
- The fixes that you want to see done to the docs.lfe.io site are _very_ involved and far beyond the scope of just the LFE source code repo
- They are also beyond the scope of the core docs for LFE provided in the LFE source code repo
- The high-level "epic" tickets listed [here](https://github.com/lfe/docs/issues/62) each have sub-tickets (and some of _those_ have sub-tickets) -- all of those tickets are focused on the "what" of 1) unifying all the LFE documentation (a fairly big problem to tackle) and 2) making that unification something that is easy, intuitive, and pleasurable to use (a much, much bigger problem to solve)
- That's the "what" -- the "how" is being covered in these tickets: https://github.com/lfe/docs3/issues ... and these tickets are aiming to generate the very first version of our static site generator that will not only pull in content from the LFE source code repo doc files, but also Gitbooks content, existing doc.lfe.io content, LFE blog post content, and maybe even Erlang docs content
- Not all of those types will be done right away, though -- we want to see some immediate results. A simple plugin-type system will allow us to easily add external sources, though, so once we have the first few, we can add more .... eventually converging on a complete LFE documentation unification

**Update**:

It may seem like there's all this work spread out ... and there is. The reason that the "how" tickets of the docs3 project aren't in the docs project is because we want to keep the current docs as they are before replacing them with something's that not ready. Both repos use the gh-pages to publish the source code, and working on v3 of the docs in the lfe/docs repo would be a confusing and useless situation for end users.

That being said, the docs3 project was created by forking from the lfe/docs project -- therefore, once we have feature parity with the v3 docs, we can merge and continue developing with the new version.

**Comment by rvirding** [comment]
I might have to unroll this one if possible. I have been having trouble with trying to fix user_guide.txt. Pandoc and the tools it uses has problems with unicode. I would like to resolve this before merging into develop.
What happens if I just reset develop to the commit before I pulled? Will everything just vanish and be lost, or what? Duncan can you still access your doc2md branch or has it vanished?

**Comment by yurrriq** [comment]
Robert, I think there's a git-revert command that preserves history but rolls back changes in a new commit.

**Comment by oubiwann** [comment]
@rvirding I still have the doc2md branch.

What specific issues have you seen with the generated `user_guide.txt`?

I saw the error messages when running `make` (e.g., `eqn:doc/man/lfe_guide.7:74: invalid input character code `159'`), but I think those are actually from `groff` ... ? Anyway, I read through the generated `user_guide.txt` file and wasn't able to find anything wonky ...

**Comment by yurrriq** [comment]
Found in `man pandoc`:

> Pandoc uses the UTF-8 character encoding for both input and output.  If your local character encoding  is not UTF-8, you should pipe input and output through iconv:
```
 iconv -t utf-8 input.txt | pandoc | iconv -f utf-8
```

**Comment by yurrriq** [comment]
My Emacs seems to think some the the .txt files are UTF-16.

**Comment by yurrriq** [comment]
@rvirding, I think I've fixed it in #213, but it requires a more recent version of `groff` than comes with OS X natively. I'm using 1.22.3, specifically, whereas my built-in version was 1.19.2.

**Update**: This [change log entry](http://git.savannah.gnu.org/cgit/groff.git/tree/ChangeLog.120#n2873) leads me to believe the `-K` option was added in version 1.20.

**Comment by rvirding** [comment]
I was getting two different sets of errors depending on whether I was
generating .txt files or .pdf files. For .txt files they were mostly
ignored but for the .pdf files the conversion stopped. I nailed it down to
a few unicode chars.

Apart from that the output looks pretty good. I will leave it for the time
being, nothing new to add in develop yet, and experiment with an updated
groff.

Robert

**Pull request merged**
