### PR TITLE
Update src/lfe_eval.erl (eval_{match_,}lambda/2)

### PR DESCRIPTION
**Pull request by yurrriq**
I was curious about [Elvis](https://github.com/inaka/elvis), the Erlang style reviewer, and needed a large body of Erlang code on which to run it, so I figured, what better codebase than LFE? In doing so, I got a bunch of boring warnings about spaces after commas and such, but the DRY warnings caught my eye. [Elvis](https://github.com/inaka/elvis) pointed out that `eval_lambda/2` and `eval_match_lambda/2` were very similar, so I decided to have a go at reducing the redundancy.

I'm not sure if this is a good approach, or if it makes any meaningful difference to lambda evaluation, but I've removed `eval_lambda/2` as well as `eval_match_lambda/2` and replaced them with `eval_lambda_expr/2`. I picked a new name to avoid potential confusion.

Some observations of the two functions:
1. They called different functions (with different arities): `apply_lambda/4` vs `apply_match_lambda/3`
2. The last two arguments passed were the same: `Vals` and `Env`
3. `eval_match_lambda` used `match_lambda_arity/1` instead of `length/1` to determine the arity.
4. Obviously, lambda forms have arglists and match-lambda forms have clauses.

The case analysis on [line 340](https://github.com/yurrriq/lfe/blob/fa6eb239716a7c456f2f9536744cb45cc902d496/src/lfe_eval.erl#L340-L347) returns a tuple of the appropriately-determined arity and a function that takes `Vals` and returns a call to `apply_{match_,}lambda`.

Next, the [case analysis of `Arity`](https://github.com/yurrriq/lfe/blob/fa6eb239716a7c456f2f9536744cb45cc902d496/src/lfe_eval.erl#L349-L370), much like before, returns functions of the appropriate arity that call the previously created `Vals`-consuming functions accordingly.

This really isn't a big change, but it's sort of nice to handle both types of lambda expression in the same place and net deletion of 41 lines feels good.

```
$ git diff --shortstat --cached src/lfe_eval.erl
 1 file changed, 34 insertions(+), 75 deletions(-)
```

P.S. I love [these](https://github.com/rvirding/lfe/blob/518d8b2d141f3522075834f7da0b29a5bd2b0fa0/src/lfe_eval.erl#L337) [comments](https://github.com/rvirding/lfe/blob/518d8b2d141f3522075834f7da0b29a5bd2b0fa0/src/lfe_eval.erl#L386):

``` erlang
%% This is a really ugly hack! But it's the same hack as in erl_eval.
```

### CODE REVIEW

**Comment by rvirding** [comment]
What were the elvis comments, especially the one about spaces after commas? I usually only have them after commas between function arguments and not after commas in data structures.

**Comment by yurrriq** [comment]
The comma comment was that there should be a space to the right of every comma, iirc.

**Comment by rvirding** [comment]
Just shows that me and elvis aren't in agreement there. :-) I will incorporate this when I get the new macro handling working.

**Comment by yurrriq** [comment]
Yeah, I have no strong feelings re: "comma space" and it was easy to disable the warnings. Merge sounds good! I'm excited to play around with the new macro stuff.

**Comment by yurrriq** [comment]
@rvirding, should I rebase?

**Comment by rvirding** [comment]
Yes, please d, it make it much cleaner.

**Comment by yurrriq** [comment]
Cool. I rebased now.

**Pull request merged**
