### PR TITLE
Enable implicit user_default functions.

### PR DESCRIPTION
**Pull request by mqsoh**
The Erlang shell will fall back on user_default functions for undefined
local functions. This change permits the same usage in the LFE shell.

This is in regards to a [Google Groups topic I opened](https://groups.google.com/forum/#!topic/lisp-flavoured-erlang/po_5kcjP1Tc).

I tried strictly following options (1) and (2), but I didn't like what I wrote. This was the most minimal change set I came up with.

### CODE REVIEW

**Comment by mqsoh** [comment]
I hope I wasn't being presumptuous in submitting a pull request. I've been feeling sort of silly about it. I _think_ it's okay; the Erlang shell uses `erlang:function_exported` but it's able to identify local functions and I didn't see a way to do that with LFE without trying and failing to execute the function.

One thing I tried was catching `undefined_function`, patching the LFE form with `[':' user_default | Expr]` and raising the initial error if that raised an `undef` error. (Also in `lfe_shell:eval_form_1`.) It felt Pythonic to me, though.

Anyway, if you want to close the request I won't take it personally. This change is serviceable for me and I can always rebase until it's provided upstream.

**Comment by oubiwann** [comment]
On Wed, Feb 11, 2015 at 11:20 PM, Mason Staugler notifications@github.com
wrote:

> I hope I wasn't being presumptuous in submitting a pull request.
> 
> Not at all! You should never feel that way :-)
> 
> I've been feeling sort of silly about it.
> 
> No need :-)
> 
> I _think_ it's okay; the Erlang shell uses erlang:function_exported but
> it's able to identify local functions and I didn't see a way to do that
> with LFE without trying and failing to execute the function.
> 
> One thing I tried was catching undefined_function, patching the LFE form
> with [':' user_default | Expr] and raising the initial error if that
> raised an undef error. (Also in lfe_shell:eval_form_1.) It felt Pythonic
> to me, though.
> 
> Anyway, if you want to close the request I won't take it personally. This
> change is serviceable for me and I can always rebase until it's provided
> upstream.
> 
> Robert's a super-busy guy (as you can imagine!), and it sometimes takes a
> while for him to check things out (I've got an open pull request that
> updates the LFE start-up banner with an ASCII LFE mug logo, and that's been
> there for a while ... and talk about silly!)

It may be a while, but Robert does eventually get around to commenting on
the PRs (sometimes the time is also due to him pondering things).

In summary: in the LFE community, silence is usually a sign of being busy
or meditating on architectures and long-term plans :-)

You might want to ping the mail list, and see what others think about it
(the more specific questions the better, e.g., "I tried solving x with y --
is that the best approach? Should I do z instead?"). Sorry of this sounds
elementary -- just tryin' to make you feel at home :-)

Thanks for the submission, and for trying out LFE!

d

**Comment by rvirding** [comment]
Yes, I will add this but I need to modify it as erlang:function_exported/3 does not load the module so I need to do an code:ensure_loaded when the shell is started.

And no, it was not presumptuous to come with a PR, or any other suggestion for that matter. And yes please use LFE and come with more comments/suggestions/bug reports/PRs/....

Final edit: what is lfe_drv.so?

**Comment by mqsoh** [comment]
I'm sorry to have neglected this. I'm closing the pull request because this change breaks the ability to see the value of a bound variable. It doesn't allow this:

```
> (set foo 'foo)
foo
> foo
foo
```

(The lfe_drv.so is compiler output on my system (Ubuntu 14.10). I'm not usually so sloppy with commits.)

**Pull request closed without merging**
