### PR TITLE
Update README.md to point to the new doc/src directory

### PR DESCRIPTION
**Pull request by yurrriq**
Similar to #223, update README.md to point to the new doc/src directory.

### CODE REVIEW

**Comment by rvirding** [comment]
Could you also add to this patch a change in updating_docs.md so it also references doc/src/*.md? Having lots of tiny PRs makes the branches look so messy. :-) And rebase it?

**Comment by yurrriq** [comment]
Certainly. I just noticed a bunch of little things. :smile:

**Comment by rvirding** [comment]
Yes, I long ago tried once to rebase after I had pulled which did work but then suddenly most of the PRs weren't pulled any more. I think it was because I made new commits when I changed the branch which unpulled the original ones. Or something like that. I have not found a clean way of both pulling and rebasing.

**Comment by yurrriq** [comment]
I think GitHub offers some help there now, but I'm skeptical. https://github.com/blog/2141-squash-your-commits

**Comment by yurrriq** [comment]
I'm going to fold #230 in this one.

**Comment by rvirding** [comment]
That looks interesting. I must try that. The worst thing that can happen is that I have to reset and lose all the pulls and your branches magically reappear. I have always had this option but it has been hidden in a menu.

**Comment by yurrriq** [comment]
Ok, sorry for the noise. This is good to go now :)

**Comment by rvirding** [comment]
No worries, just me being picky. I will now try a squash and see what happens, cross your fingers.

**Comment by yurrriq** [comment]
Actually, hang on. I'll fold the Travis updates into this. Can you set up the https://travis-ci.org end, @rvirding? You basically just have to authenticate and flip the switch.

**Comment by rvirding** [comment]
Wait

**Comment by yurrriq** [comment]
I'm on Slack if you want to discuss in real time.

**Comment by rvirding** [comment]
The squash apparently compacts all the commits into one commit, not just ff merging it into the branch. Let's try a small experiment as it is now first.

**Pull request merged**
