### PR TITLE
Auto-completion and documentation lookup for Emacs

### PR DESCRIPTION
**Pull request by bigos**
This is still work in progress, but it is already somewhat usable and ready for a discussion about moving forward. I guess we need to talk about documentation lookup integrated into the editor. Perhaps someone could have a good idea about improving exported functions lookup. And the code badly needs refactoring.

### CODE REVIEW

**Comment by rvirding** [comment]
You have discovered some errors in the documentation :-) `type-test` and `guard-bif` are no longer core forms and `include-lib` and `include-file` are macros. I was wondering if there is a better way to keep track of all these apart from listing them like this.

I might delay pulling this a bit as I want to make 1.2.2 with what we have now plus a small fix first.

**Comment by bigos** [comment]
I have created a separate repo for my personal use. So it can be tried separately and wait for the inclusion.

**Comment by bigos** [comment]
Would it be possible if the editor could ask LFE such information like supported core forms and macros? If we could do it, we wouldn't have to update editor support each time there is a significant change in LFE and we could use the same editor plugin with different versions of LFE.

For the time being, I will continue working on it in a separate repo. 
https://github.com/bigos/lfe-doc-finder

**Comment by yurrriq** [comment]
General comment: rather than shell out to `lfe` I think we should evaluate LFE code in the `*inferior-lfe*` buffer, similar to how ob-lfe does. We can come up with a "protocol" of sorts (or actually) and augment the `lfe_doc` module (or add another) for editor support. This way we could probably get some nice Vim/Atom/whatever tooling for nearly free too.

**Comment by yurrriq** [comment]
One potential issue with that is that it will muck up the history in that buffer..

**Comment by bigos** [comment]
@yurriq - could we filter the history and ignore entries from the editor support?

**Comment by yurrriq** [comment]
I know next to nothing about how the history works there, but probably. IIRC we use comint under the hood.

**Comment by deadtrickster** [comment]
how about implementing swank(-like) server? or better evaluate swank and cider and take the best parts...
because running new process each time is a bit too much as well as parsing its output.

**Comment by bigos** [comment]
I think I know how to do it. I understand why in swank the Repl is not in the inferior-lisp buffer.

**Comment by rvirding** [comment]
The is an LFE function for testing if a form is an LFE core form but nothing for going the other way and returning a list of core forms and functions.

**Comment by oubiwann** [comment]
Could we either close this PR or rebase + address review feedback?

**Comment by bigos** [comment]
I do not know what to say. It has been a while since I used LFE. I guess someone will know what is best to do.

**Comment by oubiwann** [comment]
I created a ticket to capture this work as a historical reference and as a feature request for Emacs users.

Closing ...

**Comment by mdbergmann** [comment]
It's a bit of a pity the work is lost, or kind of.

These days I guess I'd go for a language server. Together with lsp-mode or eglot in Emacs this works pretty good. I had used this in Elixir.
There is a LS for Erlang. Not sure what it means to port it.

**Pull request closed without merging**
