### PR TITLE
Add cycle function for cycled lazy sequences

### PR DESCRIPTION
**Pull request by profitware**
#278 Implement cycle function for cycled lazy sequences.

/CC @yurrriq

### CODE REVIEW

**Comment by profitware** [comment]
Hi @rvirding and @yurrriq! I've done with this small feature. Should I continue implementing features tagged [clj] after this changes be merged into develop (create new feature branch from this one) or should I branch from develop for new ones and then rebase each feature branch after every merge?

**Comment by yurrriq** [comment]
It's up to you. We've had success in the past with basing PRs on each other and merging in order. Note that @rvirding has commit rights and I don't. I'll give this a once-over later today. Could you add a comment in the appropriate spot in `doc/src/lfe_clj.3.md` and regenerate the docs (via `pandoc` and `make doc` or similar)?

**Comment by yurrriq** [comment]
This looks good, I think. Thanks for adding the documentation. Should we make it work for lazy lists too? I'm not sure. The danger there is they might be infinite. Thoughts, @oubiwann?

**Comment by rvirding** [comment]
In india now and hotel has abyssmally slow internet so I don't know when I
can pull this. Get back to you.

**Comment by profitware** [comment]
I propose to open a new issue for implementing lazy-seq function which can take list or lazy sequence and return lazy sequence as I have not found any non-infinite lazy sequence function in clj.lfe for testing how cycle/1 may handle ones.

**Comment by yurrriq** [comment]
+1 Hopefully we can find a way to incorporate a type for it once types land in LFE.

**Pull request merged**
