### PR TITLE
Make sure we install LFE includes too

### PR DESCRIPTION
**Pull request by yurrriq**
#### Before

```lfe
lfe> (progn (include-lib "lfe/include/clj.lfe") (-> 2 (+ 2)))
1: error expanding (include-lib "lfe/include/clj.lfe"): #(none file enoent)
error
```

#### After

```lfe
lfe> (progn (include-lib "lfe/include/clj.lfe") (-> 2 (+ 2)))
4
```

#### TODO

- [ ] Add a test that calls `(include-lib "lfe/include/...")`

### CODE REVIEW

**Comment by yurrriq** [comment]
@rvirding, we should merge this or something similar even without adding a test.


I'm not sure how best to test this since it requires

```fish
make install PREFIX=/path/to/somewhere
```

first then something like

```fish
/path/to/somewhere/bin/lfe -eval '(include-lib "lfe/include/clj.lfe") (-> 2 (+ 2))'
```

**Comment by oubiwann** [comment]
I'd like to see this merged; I'm okay with no test, given that it's a `Makefile` change very little chance of an impact (except the indented one). 

I have confirmed that the failing tests were a result of an old state, and that 1) the latest LFE runs pass without issue, and 2) a rebase upon latest for this branch passes without issue (see https://travis-ci.org/oubiwann/lfe/builds/529357849).

Instead of a "Merge pull request", if we do a "Rebase and merge", everything will be fine.

Thoughts?

**Review by oubiwann — APPROVED** [review]

**Comment by yurrriq** [comment]
I'm fine with that. It's exciting to see all this activity on LFE 😄 Thanks for all your work!

**Comment by yurrriq** [comment]
I've rebased and force pushed. Hope that helps.

**Comment by oubiwann** [comment]
Closing this in favour of a new branch that cherry-picks the commit from this one (see #409).

**Pull request closed without merging**
