### PR TITLE
Color shell banner

### PR DESCRIPTION
**Pull request by oubiwann**
Building upon the other branch for supporting a [new shell banner](https://github.com/rvirding/lfe/pull/102), this one adds color :-)

### CODE REVIEW

**Comment by oubiwann** [comment]
Here's what the color shell banner looks like :-)

screen shot 2015-09-20 at 9 45 45pm

**Comment by oubiwann** [comment]
Note that if you want to merge this branch, the non-coloured ASCII branch needs to be merged first (this one depends upon that one). See PR #102 ...

**Comment by yurrriq** [comment]
:+1:

**Comment by oubiwann** [comment]
@rvirding Any chance of getting this banner into LFE 1.0? :-)

**Comment by unbalancedparentheses** [comment]
Isn't a little way too big? It might be better to use when you ask for the version of lfe

**Comment by oubiwann** [comment]
That's what I would have thought at first. The idea came from Julia's banner which I thought was a bit large at first. Then, after using it for a while, I realized I was having the same positive associations I used to have when signing on to the DEC Alpha UNIX machines in the early 90s as well as the MUDs and BBSs :-) Then I was hooked, and I wanted the same great feeling when starting up LFE :-)

Here's a Julia screenshot:
julia

Note the similarity in size ...

**Comment by rvirding** [comment]
Julia's is a bit smaller. :-) What if we cut out the steam from the mug? It's not in the "official" mug or sticker.

**Comment by oubiwann** [comment]
Hehe :-) Sure, let me give it a shot, see what we can get ...

**Comment by oubiwann** [comment]
Okay, I've updated the branch to squeeze as much room as possible. Here's what it looks like now:
lfe

It's only one more line than the Julia banner, but the text lines and vertical bar are the same size.

**Comment by rvirding** [comment]
A big +1 here. Another feature for 1.0.

**Comment by oubiwann** [comment]
Sweet!!!

**Comment by yurrriq** [comment]
Nice!

**Comment by rvirding** [comment]
I have pulled it and it is now coming in the next release. It looks good. One change I would like to make is to explicitly make the mug green like the logo. Now it comes out black with my default terminal.

**Pull request merged**
