### PR TITLE
New prompt

### PR DESCRIPTION
**Pull request by oubiwann**
This branch makes a small change to `lfe_shell.erl` to support a user-settable LFE prompt. See ticket #236 for example usage, etc.

Note that in the above-mentioned ticket, @yurrriq made a very interesting suggestion: making the prompt settable while running (this could be utilized nicely latter if we wanted to implement multiple user environments in a single LFE REPL instance, updating the prompt dynamically when switching between them).

However, the current state of the LFE REPL (shell) server doesn't seem quite up to that task (at least not easily).

One final note: this change also includes some cleanup: as I was going through the files, I discovered some mixed tabs/spaces and trailing whitespace.

### CODE REVIEW

**Comment by yurrriq** [comment]
Some of the indentation changes look incorrect to me, at least on GitHub. Specifically I mean some instances of `let`, `let*` and `fletrec`.

**Comment by oubiwann** [comment]
@yurriq Ugh, yeah ... looks like it. I'm pushing up fixes for the fixes (I just did a s&r for `\t` -> 4 spaces ... looks like that wasn't quite enough). Let me know if there are any I missed.

**Comment by rvirding** [comment]
\t -> 8 is the standard, and i never change that in my code. That doesn't
work for comments though.
 If you use emacs the easiest is to call untabify on the buffer.

**Comment by yurrriq** [comment]
We still gotta fix Emacs's handling of the various `flet` forms... There's been some serious jag ska bara impeding progress there though 😆

**Comment by yurrriq** [comment]
Ping.

**Comment by oubiwann** [comment]
@rvirding I've just rebased to remove conflicts. What do you think of this change? Can we merge it?

**Comment by oubiwann** [comment]
Reminder: this branch has a ticker where features and changes were discuses here:
- issue #236

**Pull request merged**
