### PR TITLE
Update erllibs

### PR DESCRIPTION
**Pull request by oubiwann**
Libraries in ~/.lfe/libs weren't getting found. This change fixes that.

### CODE REVIEW

**Comment by rvirding** [comment]
I wonder if you really need to do the LFE_HOME_LIBS bit? ERL_LIBS does look down two levels for an ebin directory, or am I missing something here?

**Comment by oubiwann** [comment]
Is that functionality intended to support only releases? Because in all the work I've done with non-release- based libraries, that has never worked. Maybe I've been doing it wrong?

**Comment by oubiwann** [comment]
In particular, for this change, I tried loading a module from `~/.lfe/libs/lutil`, and it didn't load. When I looked at the `ERL_LIBS` definition in `lfe`, I knew why (based on my previous experience with this). As soon as I added the `deps/*`dirs to `ERL_LIBS` in `./bin/lfe`, the module was found without issue.

**Comment by oubiwann** [comment]
Okay, I've cleaned up the branch (but managed to automatically close the PR from the command line by accident ...).

Let me know what you think of these rules of precedence.

**Comment by rvirding** [comment]
That is looking better. I am a bit uncertain about including PROJ_LIBS and R3_PROJ_LIBS by default. Shouldn't they be left to the user to include. I think we should only add LFE stuff to ERL_LIBS.

**Comment by oubiwann** [comment]
Yeah, I was on the fence about that for a while, but it was something else I thought about this weekend. I'm now in favor of it because I couldn't think of any way in which it hurt matters, and the benefits are strong:
- without it, users would have to manually update their `ERL_LIBS` (a poor user experience)
- with it, they can start up a project managed with erl.mk, rebar, rebar3, or lfetool and they will have access to everything the expect to
- with it, lfetool can stop managing the `ERL_LIBS`
- lfetool `Makefile` includes get much simpler
- lfetool bootstrapping gets simpler

**Comment by rvirding** [comment]
Mutter, mutter, mutter, ok then.

**Comment by yurrriq** [comment]
:laughing: :+1:

**Comment by rvirding** [comment]
Need a serious quick fix for this as find complains if its search directories don't exist. I get:

```
~/lfe/lfe$ lfe
find: ./deps: No such file or directory
find: ./_build/default/deps: No such file or directory
find: /Users/rv/.lfe/libs: No such file or directory
Erlang/OTP 18 [erts-7.0] [source-4d83b58] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

LFE Shell V7.0 (abort with ^G)
> 
```

**Comment by oubiwann** [comment]
Looking at it now ...

**Comment by rvirding** [comment]
I wonder if the directory should be called ~/.lfe/lib instead to mirror the lib directory in an erlang release?

**Comment by oubiwann** [comment]
I can do that; it will require a change to lfetool, but there's no reason I can't do that :-)

(lfetool is currently set up to sync to released versions, so this change shouldn't break any old projects)

**Comment by oubiwann** [comment]
Hehe -- looks like we both worked on it :-)

I'm cool with your version/changes -- we can ignore/close #155.

**Pull request merged**
