### PR TITLE
Add the do_docs compiler pass

### LINKED ISSUE #211: Saving documentation in the .beam file
We are now working towards saving the module, function and macro documentation strings in the .beam file. As a first step along the way the `define-function` and `define-macro` core forms not have an extra element for the documentation strings. The macro expander now saves the documentation string from the `defun` and `defmacro` in the forms when they are expanded. The doc strings are then passed through the compiler where they are ignored except in the lint pass where they are checked that they are either list character strings or binaries.

It is @yurrriq who is doing the actual work around this.

I think the based place to get these strings is after the split pass and before the expand pass in the compiler because between these two the macro definitions are still in the code forms. After the expand pass all macros have been expanded and their definitions are no longer saved. Then they have to be saved of course which is where it starts getting interesting. :-)

You can actually comment local function and macro definitions:

```
(flet ((sune (a b)
         "The sune function."
         (* a b)))
  ...)
```

However, these comments are lost, mainly because I don't know what to do with them.

### PR DESCRIPTION
**Pull request by yurrriq**
Add the `do_docs` compiler pass, which prepares and writes the `"LDoc"` beam chunk in every compiled module, unless the `no-docs` flag is set. Closes #211.

N.B. This also includes some tooling updates, mostly w.r.t. rebar3, but that shouldn't affect anything negatively. Famous last words...

### CODE REVIEW

**Comment by yurrriq** [comment]
Is there anything blocking this?

**Comment by yurrriq** [comment]
This should be good to go now, @rvirding.

**Comment by yurrriq** [comment]
The [changes to rebar.config](https://github.com/rvirding/lfe/pull/216/files#diff-7) may break old `rebar` builds, i.e. not `rebar3`.
It looks like we aren't using either any more though.

The added bonus is the following commands now work:

``` sh
$ rebar3 ct
$ rebar3 eunit
$ rebar3 proper
```

... which may be useful to @arpunk (see his [comment](https://github.com/rvirding/lfe/pull/168#issuecomment-167680098)), among others.

**Comment by yurrriq** [comment]
I'm going to write some macros today that generate record accessors. I'd love to have the resultant functions/docstrings end up in the LDoc chunk. If that's not the case, we should consider moving the `do_docs` pass.

**Comment by yurrriq** [comment]
Levaindoc's [`defconversions`](https://github.com/quasiquoting/levaindoc/blob/master/include/conversions.lfe) is a good example too, though there are no docstrings there at the moment.

**Comment by rvirding** [comment]
I will merge it tonight or tomorrow then we can check where is the best place to put do_docs and I will make any necessary changes to the compiler.

This feels good.

**Comment by yurrriq** [comment]
Sounds good to me. :smile:

**Comment by yurrriq** [comment]
Confirmed. Macro-generated functions show up in the LDoc chunk.

**Pull request merged**
