### PR TITLE
Remove duplicate entries from EBINS during install-beam target

### PR DESCRIPTION
**Pull request by starkertyp**
Hi,
as mentioned on #342 make install fails on my gentoo system because make install tries to install lfe_scan.beam twice.
During the whole compilation magic src/lfe_scan.xrl will get turned into src/lfe_scan.erl . As EBINS is essentially a list of all .erl, .xrl and .yrl files with the endings replaced by .beam this results in the problem that EBINS will contain lfe_scan.beam twice as this name is generated from both the .xrl and the .erl file. As this problem seems to affect the install target I tried not to mess with anything else (I don't know a lot about make).

This fix is kinda ugly but it resolves the issue for me. Not sure if this will work well on other systems but it might be worth a shot.

### CODE REVIEW

**Comment by yurrriq** [comment]
Is there a way we could use `$^` rather than shelling out?

**Comment by yurrriq** [comment]
Due to the implicit rules it looks like no. It also seems like if we simply remove the xrl part from EBINS then all will be well, maybe. According to a quick search on my phone, we don't have any `.yrl` files either, so maybe we could remove or comment out the related parts of the Makefile for clarity.

**Comment by starkertyp** [comment]
Removing the .xrl part results in lfe_scan.beam not being generated on my system, which is why I tried this solution.

**Comment by yurrriq** [comment]
Ah ok.

**Comment by oubiwann** [comment]
I'm going to take a look at this, but I'll probably close this PR, cherry pick the commits, and work on the issue in a new branch (i.e., any commits made so far will get full credit 😉).

**Comment by oubiwann** [comment]
I've cherry-picked the original commit for this into a new PR on the LFE 2.0 branch).

Closing ....

**Pull request closed without merging**
