### PR TITLE
Remove rebar from LFE.

### PR DESCRIPTION
**Pull request by oubiwann**
In preparation for v1.0 release.

Addresses issue #197.

### CODE REVIEW

**Comment by rvirding** [comment]
What does the addition to bin/lfe do?

**Comment by oubiwann** [comment]
Oh dear, I don't think I pushed after I fixed that (it was an experiment I had been working on to get an LFE persistent history over REPL restarts ... I got it working for Erlang, but not LFE).

I'll push up the updated branch which removes that accidental commit ...

**Comment by oubiwann** [comment]
Okay, the latest pushed fixed that.

**Comment by rvirding** [comment]
Could you merge PRs #196 and #198 and rebase them and I will pull them?

**Comment by oubiwann** [comment]
Done. 

This fixes the following issues:
- #188
- #192
- #195
- #197
- #198 (now merged into this branch)

**Pull request merged**
