### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bigos**
banner rainbow delimiters fix

### CODE REVIEW

**Comment by yurrriq** [comment]
Related: #215

**Comment by yurrriq** [comment]
**Note**: Robert has addressed this with c6b3e06.

**Comment by rvirding** [comment]
When you come with more PRs please make them merge into develop not master. I basically don't do PRs into master. But keep coming.

**Comment by bigos** [comment]
understood

**Comment by rvirding** [comment]
This was fixed in c6b3e060951aec3e618a54118817c94b62b1505b

**Pull request closed without merging**
