### PR TITLE
Update erl_parse deprecated function calls

### PR DESCRIPTION
**Pull request by arpunk**
Hello @rvirding 

The following removes the deprecations on `lfe_qlc.erl` module. I've tested this on Erlang/OTP 17.5 and 18.1 but I haven't get the test suite to run properly.

### CODE REVIEW

**Comment by rvirding** [comment]
Which test suite? It would need some fixing so that it would still compile on older erlang systems form before these changes were made. Another solution would be to use a later version of the qlc.erl file but unfortunately the file does have to be modified so that LFE can use it; a call has to be added.

**Comment by arpunk** [comment]
I meant the tests under `tests/` directory. I wanted to run the whole suite to see if the changes break the current tests.

What we can do is try to update the `qlc.erl` file that is being shipped currently in latest Erlang and we backport the LFE changes again but I do not think it's necessary.

This raises a question. What would be the oldest Erlang version that LFE will support?

**Comment by rvirding** [comment]
I checked and the new functions in erl_parse and the erl_anno module you use first came in 18.

**Comment by rvirding** [comment]
I have written an entry in the mailing list about using Common Test and LFE.

**Comment by arpunk** [comment]
@rvirding I'm sorry for missing this.

I tried it on Erlang 17.5 and got the same deprecation calls. Maybe I should have tried on earlier versions.

By running the test suite I was under the impression I could easily do `rebar3 ct` or `rebar3 eunit` and get the tests running.

**Comment by arpunk** [comment]
This is no longer needed since the `lfe_qlc.erl` file got removed on a recent commit.

**Comment by rvirding** [comment]
Yes, that was reason I made the change. I hadn't really bothered about it until the deprecations became serious. Hopefully this new way will keep working in the future.

**Pull request closed without merging**
