### PR TITLE
Fix expansion for comparison macros for 3 or more arguments

### LINKED ISSUE #445: == macro expansion is incorrect
For example:
```lisp
(== 1 1) => true
(== 1 1 1) => false
```
This is because the macro expansion for `(== 1 1 1)` is
```lisp
(== (== 1 1) 1)
```
which won't be `true` because the inner `(== 1 1)` is `true` which is not equal to `1`. i.e. `(== 'true 1) => false`.

This is also the case for `=:=`.

### PR DESCRIPTION
**Pull request by yastanotheruser**
The `exp_comp` function was updated to bind operands to variables and then compare the variables in successive pairs. Fixes #445.

### CODE REVIEW

**Comment by rvirding** [comment]
Have you any more changes you would like to make? I have one suggestion and that is don't import `lists:zip` and `lists:droplast` but call them with the module explicitly. I am slowly migrating away from importing functions from modules to being explicit in the code.

**Comment by yastanotheruser** [comment]
nope, looks okay

**Comment by rvirding** [comment]
This seems to work as it should but the checks on OTP 19/20/21 haven't been run. I don't know why.

**Comment by oubiwann** [comment]
@rvirding looking into CI/CD now ...

**Comment by oubiwann** [comment]
@rvirding I opened a ticket for this here: https://github.com/lfe/lfe/issues/472

**Pull request merged**
