### PR TITLE
Fix banner version error

### PR DESCRIPTION
**Pull request by oubiwann**
This should fix issue #192 and #195.

### CODE REVIEW

**Comment by rvirding** [comment]
How about an escript which mimics what rebar does? We just must make sure we don't clash with rebar. This might be overkill though.

**Comment by oubiwann** [comment]
Hrm... that might be a bit much? An extra executable when a `make` target would do?

**Comment by rvirding** [comment]
But i want to copy it and add all the modules and ... You are quite right of course. :-)

**Comment by rvirding** [comment]
Could you merge PRs #196 and #198 and rebase them and I will pull them?

**Comment by oubiwann** [comment]
Yup, good idea. I'm going to close this ticket in favor of merging everything into the drop-rebar branch (#198).

**Pull request closed without merging**
