### PR TITLE
Update makefile

### LINKED ISSUE #301: Update Makefile
Pulled out from the thread on #244.

- [x] ~~Decouple `install-man` from `install` (thus obviating the *need* for `pandoc`)~~
- [x] Fold in some of the [Elixir `Makefile`](https://github.com/elixir-lang/elixir/blob/v1.3.4/Makefile#L99)-inspired changes from the [LFE Nix package](https://github.com/NixOS/nixpkgs/blob/16.09/pkgs/development/interpreters/lfe/default.nix#L19)

### PR DESCRIPTION
**Pull request by yurrriq**
See commit messages for details. Closes #301, #250 and #77.

### CODE REVIEW

**Comment by yurrriq** [comment]
Rebased.

**Comment by yurrriq** [comment]
Rebased again.

**Comment by rvirding** [comment]
But not after pulling your other PR. Is it ok if I do a rebase on this?

**Comment by yurrriq** [comment]
I've rebased on `develop` again now :)

**Comment by rvirding** [comment]
Merci!

**Pull request merged**
